services:
  usgovernment-warrior:
    image: atdr.meo.ws/archiveteam/usgovernment-grab
    command: --concurrent 20 blitzwing
    deploy:
      mode: replicated
      replicas: 700
    cpus: 3
    ports:
      - "9010-9730:8001"
    logging:
      driver: none
    restart: unless-stopped
    cpu_shares: 64 # highly recommend you dont change this
